### ISSUE TITLE
issue with email signup

### ISSUE THREAD

**Issue by nigelfig** [wsvincent/djangox#10]
@wsvincent 

user's username is set to the part of email before @. Because of this if someone signs up with email john@gmail.com, they are assigned username john. If someone else tries to sign up with email john@hotmail.com, they get an error.

**Comment by signaleleven** [comment]
Not in my experience. By chance I just tried exactly that, and the second user got a number added to the username (john79, for instance)

**Comment by wsvincent** [comment]
I agree with @signaleleven . It should randomly add a string if the same username part--so `john` in @nigelfig 's example.

There's more I could say on this. Basically django-allauth is kinda faking username's and if you use BaseUserManager it's possible to totally remove username from your project. But until you have 100s of users with the same name this approach is fine. Keep it simple :)

**Comment by nigelfig** [comment]
Ah ok thanks. I tried to remove the debug toolbar package from project, and must have affected sign up form some how.
