### ISSUE TITLE
static setting update

### ISSUE THREAD

**Issue by amirreza8002** [wsvincent/djangox#102]
-----------------------------
STORAGE = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"
    },
}
-------------------------------

this goes in place of:
-----------------------
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
-----------------------

per django 4.2 release
https://docs.djangoproject.com/en/4.2/releases/4.2/#custom-file-storages

**Comment by wsvincent** [comment]
Yes you are correct @amirreza8002! Good catch. I will do a PR to fix shortly. Thank you for bringing it to my attention.
