### ISSUE TITLE
Missing template tag: bootstrap_form

### ISSUE THREAD

**Issue by motatoes** [wsvincent/djangox#11]
In the [password_set.html](https://github.com/wsvincent/djangox/blob/master/templates/account/password_set.html#L9) file the form is rendered using the `bootstrap_form` tag which is not loaded, and is not part of the pipfile requirements. Should this be replaced with `{{ password_set_form | crispy }}` ?

**Comment by wsvincent** [comment]
Yes! Nice catch. Now fixed.
