### ISSUE TITLE
navbar collapse toggle button 

### ISSUE THREAD

**Issue by makai77** [wsvincent/djangox#110]
I love djangoX.
Have you considered adding a navbar toggle button for mobile devices or small screens?

**Comment by wsvincent** [comment]
Thanks for the kind words. Doesn't it already toggle on smaller screens with Bootstrap?

**Comment by makai77** [comment]
It does not not, which is not optimal for mobile devices. So I had to add
some code to make that happen. Overall I love the experience and it's
simplicity for begginers.
