### ISSUE TITLE
Template customization

### ISSUE THREAD

**Issue by raybesiga** [wsvincent/djangox#18]
Hi @wsvincent 

Thank you for this fabulous project. Just wondering if you plan to make the repo more like a cookiecutter such that a user can specify the project name and other variables as they set it up instead of just cloning and then editing the different project files. 

Only an inquiry. Best regards.

Ray

**Comment by wsvincent** [comment]
Hi Ray,

Thanks for the comment. So...I think cookiecutter is great but you can already do that now actually. Just find/replace any mention of "djangox" in the codebase. I think there's a half dozen spots, max for that. Something I should add to the Readme actually...
