### ISSUE TITLE
Cannot import name 'python_2_unicode_compatible'

### ISSUE THREAD

**Issue by Pyrross** [wsvincent/djangox#20]
Having tried to `makemigrations users` in different ways, I still get an ImportError:

`ImportError: cannot import name 'python_2_unicode_compatible' from 'django.utils.encoding' (C:\Users\pyrro\.virtualenvs\djangox-wr5bj6HE\lib\site-packages\django\utils\encoding.py)`

I honestly don't understand why. I am using the correct versions.

**Comment by aTastyCookie** [comment]
+1

**Comment by Ardenine** [comment]
@wsvincent you should upgrade the django-allauth version to the 0.41.0

I fixed it in my forked version of djangox : https://github.com/Ardenine/djangox/pull/1/commits/3e7f1eeafed93f2ecaeedf8bfb8d5d18531a1fe4


Cheers

**Comment by rwflick** [comment]
I have been running into this problem and I was able to fix it by upgrading the version of allauth to 0.41.0.

**Comment by wsvincent** [comment]
I just updated the packages, especially allauth to 0.41.0. Thanks all for the help!
