### ISSUE TITLE
djangoX Logo File Missing

### ISSUE THREAD

**Issue by rwflick** [wsvincent/djangox#33]
This is not a big deal but when you run the install for the first time everything works but the logo file is missing from the static/images folder so the home screen does not look like it does in the instructions.  Again, it's not a big deal and I was able to find the logo.png file on Google but I just thought I'd mention it.  (BTW, I really like the new setup with the "config" app so that it is much easier to change the name!

**Comment by wsvincent** [comment]
Ah, odd. I guess "static" got into the .gitignore file somehow and wasn't included. Just fixed! Thanks for letting me know.
