### ISSUE TITLE
User Signup -- Password2 field

### ISSUE THREAD

**Issue by eezis** [wsvincent/djangox#36]
Shouldn't the signup form have email, password and a password2 field to ensure that the user didn't make a typo while entering their password? If they make that simple mistake and then they try to login, they will fail. And of they try to create a new account that will fail too because the email field will be taken.

**Comment by eezis** [comment]
Nevermind, in settings.py

`ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE = True`

**Comment by wsvincent** [comment]
No worries! I appreciate you asking.
