### ISSUE TITLE
Can we have an example, on how to have minimalist DB table?

### ISSUE THREAD

**Issue by yccheok** [wsvincent/djangox#4]
I run through your example, I notice that the generated table is as following

     id | password |  last_login  | is_superuser | username | first_name | last_name | email | is_staff | is_active | date_joined

If I use the example of https://docs.djangoproject.com/en/2.1/topics/auth/customizing/#a-full-example , it produces a more minimalist 

     id | password | last_login | email | is_active | is_admin

May I know why is it so? Is it because the example is using `AbstractBaseUser`, and your example `AbstractUser`? If it is so, is it possible to use `AbstractBaseUser` with django-allauth? I tried to use it, but it seems like it is complaining missing username field.

**Comment by wsvincent** [comment]
Hi, I cover how to customize the user model at length in djangoforbeginners.com. You might also look at some tutorials I have on this:

https://wsvincent.com/django-custom-user-model-tutorial/
https://wsvincent.com/django-allauth-tutorial-custom-user-model/
