### ISSUE TITLE
Adding markdown

### ISSUE THREAD

**Issue by Simvolick** [wsvincent/djangox#42]
Do you want to add Markdown as something available at the start of the project? If any website will be dealing with text, markdown for sure is a great option.

**Comment by wsvincent** [comment]
Hi @Simvolick, 

Markdown is very useful in a lot of projects. I've implemented it on LearnDjango.com for example. The issue, I think, is that markdown can be done a number of different ways. Either via 3rd party packages, raw, and then do you need a WYSIWG editor for users or is it just for staff?

In any event, markdown is beyond what I think a starter template should have. But if you decide to implement and are willing to share code I'd be curious to see how you handle.
