### ISSUE TITLE
404 for assets after first launch

### ISSUE THREAD

**Issue by KrunchMuffin** [wsvincent/djangox#5]
I am somewhat new to Python/Django. I have followed your tuts in the past.
Saw that you created a project bootstrap. Wanted to give it a try. 
I get 404 on all the assets for some reason even though they are there.

![image](https://user-images.githubusercontent.com/1037197/47338091-9afac700-d664-11e8-82f6-534755186260.png)

**Comment by KrunchMuffin** [comment]
Well, I fixed it by adding this, but I must have done something wrong for this to happen?

``` 
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static")
] 
```

**Comment by wsvincent** [comment]
Aww, yup, good catch. I've added STATICFILES_DIRS so others who run `collectstatic` won't hit this issue, too.

In truth I use a more complicated version of DjangoX but I want to keep this project as real-world but also basic as possible. 

Thanks again for taking the time to submit an issue!
