### ISSUE TITLE
Add ACCOUNT_SIGNUP_FORM_CLASS to settings.py

### ISSUE THREAD

**Issue by NikolaiT** [wsvincent/djangox#6]
The custom user creation form right now is ignored.

Add this to settings.py:

```
ACCOUNT_SIGNUP_FORM_CLASS = "users.forms.CustomUserCreationForm"
```

**Comment by robsonsilv4** [comment]
There is also a new way of doing this:

`ACCOUNT_FORMS = {'signup': 'users.forms.CustomUserCreationForm'}`

I just made the pull request with this addition, I hope @wsvincent accepts.

**Comment by wsvincent** [comment]
Just added it. Thanks @NikolaiT and @robsonsilv4 for bringing it to my attention.
