### ISSUE TITLE
Docker installation still uses sqlite

### ISSUE THREAD

**Issue by vlejd** [wsvincent/djangox#63]
When following instructions setup with docker, it correctly creates postgres containers, but django still uses sqlite. 
Can we a) add note that you need to do it manually b) remove postgres from docker compose c) add instructions on how to add it ? 
I am happy to make a PR.

**Comment by wsvincent** [comment]
Yes you're right. I'm going to update that tomorrow. I agree can/should have PostgreSQL for Docker.

**Comment by wsvincent** [comment]
Ok, updated. I went for as simple an implementation as I could. Adding `pyscopg2-binary`, updating `docker-compose.yml`, and a note on updating the `DATABASES` section. Let me know what you think!
