### ISSUE TITLE
Deprecation Warning

### ISSUE THREAD

**Issue by KrunchMuffin** [wsvincent/djangox#8]
Is this djangox related?

> virtualenv.py:1041: DeprecationWarning: the imp module is deprecated in favour of importlib; see the 
   module's documentation for alternative uses
  import imp

**Comment by wsvincent** [comment]
Not related to DjangoX specifically. Seems like [an issue with virtualenvs](https://github.com/pypa/virtualenv/issues/955) and newer versions of Python.

Thanks for bringing it up!
