### ISSUE TITLE
Use pipenv install instead of pip inside Dockerfile

### ISSUE THREAD

**Issue by mabdullahabid** [wsvincent/djangox#80]
As the subject states, what are your thoughts on using pipenv install inside the Dockerfile instead of pip?

**Comment by wsvincent** [comment]
Dockerfile works well loading a requirements.txt file. I had lots of issues with a lockfile that might be generated locally vs within Docker, but that is probably easy enough to fix. Pipenv only just added a [native way to generate requirements.txt](https://github.com/pypa/pipenv/issues/4959) so it's probably fine, I'm just used to using Pip and haven't had issues with that approach.
